const SET_CURRENT_PROFILE = 'SET_CURRENT_FILE';
const GET_LIST_PROFILE = 'GET_LIST_PROFILE';
const ADD_PROFILE = 'ADD_PROFILE';
const RENAME_PROFILE = 'RENAME_PROFILE';
const DELETE_PROFILE = 'DELETE_PROFILE';
const SWITCH_PROFILE = 'SWITCH_PROFILE';

export {
  SET_CURRENT_PROFILE,
  GET_LIST_PROFILE,
  ADD_PROFILE,
  RENAME_PROFILE,
  DELETE_PROFILE,
  SWITCH_PROFILE,
};
